server:
  port: 8022
spring:
  devtools:
    restart:
      enabled: false #是否支持热部署
      additional-paths: src/main/java #设置重启的目录
      exclude: WEB-INF/** #classpath目录下的WEB-INF文件夹内容修改不重启

  thymeleaf:
    cache: false
  application:
    name: zhuanhuan
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/taotao?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    druid:
      initial-size: 1
      min-idle: 1 #最小空闲连接
      max-active: 20 #最大活动连接
      test-on-borrow: true #获取连接时测试是否可用
      stat-view-servlet.allow: true #监控页面启动
mybatis:
  # mybatis 别名扫描
  type-aliases-package: cn.tkl.dockTkl.pojo
  # mapper.xml文件位置,如果没有映射文件，请注释掉
  mapper-locations:  classpath:cn.tkl.dockTkl.mappers/*.xml
  # 测试1

